Repository openshift-eng/art-bot, pull requests merged in 2024-07, with the labels that each got.

#188 ART-10035: use pr target branch when check commits
  artbotlib/pr_in_build.py
Labels: lgtm, tide/merge-method-squash, approved, jira/valid-reference

#189 added new reviewer/approver
  OWNERS
Labels: lgtm, approved

#190 ART-9985: art-bot notifies of all builds for a PR
  artbotlib/pr_in_build.py
Labels: lgtm, approved, jira/valid-reference

#191 Rotate keytab
  artbotlib/kerberos.py
Labels: lgtm, approved

#194 show only images which should be in payload
  artbotlib/pr_in_build.py
Labels: lgtm, approved

#195 [ART-10106] get build nvr from db
  artbotlib/pr_in_build.py
Labels: lgtm, approved
