Repository openshift-eng/art-bot, pull requests merged in 2024-01, with the labels that each got.

#164 ART-8559 Use payload_name when determining imagestream tag
  artbotlib/pipeline_image_util.py
Labels: lgtm, approved

#166 Improve brew list
  artbotlib/brew_list.py
  tests/test_brew_list.py
Labels: lgtm

#168 ART-8704: fixed URL construction for distgits
  artbotlib/brew_list.py
Labels: lgtm, approved, jira/valid-reference

#169 ART-8042 Enable elliott go report
  artbotlib/elliott.py
  artbotlib/help.py
  artbotlib/regex_mapping.py
Labels: lgtm, approved

#170 Refresh kerb credentials before image_list()
  artbotlib/elliott.py
Labels: lgtm, approved
